### ISSUE TITLE
Keyboard access?

### ISSUE THREAD

**Issue by helmadik** [dspinellis/word-master-ancient-greek#3]
My final one for now, sorry:-)  Is there a chance we might use the keyboard for typing at some point? I do think the capitals are brilliant.

**Comment by dspinellis** [comment]
Both the on-screen and the hardware keyboard of Windows (set to Modern Greek) work fine for me.

**Comment by helmadik** [comment]
Φοργετ what I said!! I never realized the choice of keyboard would make a difference. Works fine with polytonic on Mac as well.
